Feature/post1.0 feat: 공지사항 생성, 공지사항 읽기 기능 추가
wafflestudio/csereal-server pull request #1
Opened 2023-07-23 06:56 UTC by skfotakf

일단은 얼개를 잡는게 중요할 거 같은데 딱히 지금 새롭게 올라온 게 없어서 먼저 만들어봤습니다
일단 공지사항과 새소식을 core.post 패키지에 담았고 이제 앞으로 core 패키지 밑에 user, professor, image 등의 패키지를 담는걸 기본 방향으로 잡았습니다
각각의 패키지 아래에는 api, database, dto, service가 있고
그리고 기본 기능이 만들어졌는데, 아직은 createdAt, modifiedAt이 반영안되는 오류가 있고
기존의 filterChain으로는 자꾸 forbidden이 떠서 새롭게 securityFilterChain을 가져오니까 잘 되었는데, 저렇게 해도 앞으로 괜찮은지는 사실 저도 아직 잘 모르겠어요
그래도 지금 핵심 기능인 공지사항 생성, 공지사항 읽기는 잘 되고 있습니다. 이미지 첨부합니다
브랜치는 기존에 합의된대로 develop에 develop 브랜치에 보냅니다 

제가 기본 얼개를 함께 짜둔채로 제출하다보니까 당황스러운 부분도 있을 거 같아요. 개선시킬 부분이 있다면 피드백해주세요 

![image](https://github.com/wafflestudio/csereal-server/assets/86216809/cefee9b4-bc9e-4e2d-8fe3-d0077fdd638c)
![image](https://github.com/wafflestudio/csereal-server/assets/86216809/ee8dbd1b-4f08-4792-893a-8ab36542f0ac)

2023-07-23 07:46 UTC, huGgW requested changes
추가적으로 .idea는 intellij 설정 관련 파일이라서 git에서는 없애는 것이 좋을거 같은데... 다른 분들 어떠신지 궁금합니다...!

2023-07-23 07:46 UTC, huGgW commented on src/main/resources/application.yaml
> +    password: toor
여기는 docker compose로 실행할 때 자동으로 설정되도록 해놓았습니다.
해당 내용 삭제해주시면 감사하겠습니다!

2023-07-23 07:46 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/post/service/PostService.kt
> +    // 아직 날짜가 제대로 안 뜨는 문제점
이런 경우 comment에 TODO: ... 로 남겨주시면 좋을 거 같아요!

2023-07-23 07:46 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/post/service/PostService.kt
> +        val post: Optional<PostEntity> = postRepository.findById(postId)
findByIdOrNull을 사용해서 ? 연산자를 활용하는 것이 Kotlin에서 코드 작성 시 더 좋아보입니다.

2023-07-23 07:46 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/common/Exceptions.kt
> +}
open class 안에 class로 정의하신 이유가 있으신가요?

2023-07-23 07:47 UTC, huGgW commented
아 그리고 PR 이름은 앞에 버전 없이 Feat: 내용 이런 식으로 가는게 깔끔해 보이기는 하는데요...? 어떠신가요

2023-07-23 08:30 UTC, leeeryboy requested changes
엔티티 네이밍 건의사항이 있는데, 우리가 테이블을 분리하자는 얘기가 나왔었으니까 post 같은 제너럴한 네이밍보다는 공지사항이면 notice 같이 특정해주면 좋을듯 + uri 도 node 대신 notice?

2023-07-23 08:30 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/post/service/PostService.kt
> +    }
1. 읽기만 할때는 Transactional 어노테이션에 readonly = True 기본으로 주면 좋을듯
2. 코틀린은 null 처리를 따로해서 자바 Optional을 굳이 쓸 필요가 없음
```
val post = postRepository.findByIdOrNull(postId)
            ?: throw CserealException.Csereal400("존재하지 않는 질문 번호 입니다.(postId: $postId)")
        return PostDto.of(post)
```

2023-07-23 08:30 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/post/service/PostService.kt
> +    // 아직 날짜가 제대로 안 뜨는 문제점
어플리케이션 클래스에 @EnableJpaAuditing 안붙여서 그런거지 않을까 하는 의심

2023-07-23 09:13 UTC, skfotakf commented
리뷰 잘 확인했고 수정해서 올렸습니다
다만 open class는 예전에 본걸 그대로 올린거고, 잘 모르겠어서 일단 그대로 놔뒀습니다
또 env는 제가 맞게 했는지 확신이 없네요, docker compose를 어떻게 하는건지 알아봐야할 거 같습니다 ㅠㅠ

2023-07-23 11:07 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +        // TODO():"아직 날짜가 제대로 안 뜸"
`TODO():` 가 아니고 `TODO:`로 수정해주시면 좋을거 같아요!

2023-07-23 11:08 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +        return NoticeDto.of(newPost)
변수명도 헷갈리지 않게 다 notice, noticeId 로 바꿔주면 좋을듯

2023-07-23 13:26 UTC, skfotakf commented
말씀하신 내용들 수정해서 다시 리뷰 올렸습니다
앞으로는 저런거로 번거롭게 pr 더 안하도록 꼼꼼히 확인하겠습니다

2023-07-24 01:44 UTC, leeeryboy approved these changes
굳굳 수고했어용

2023-07-25 02:57 UTC, huGgW approved these changes
수고했어요!

2023-07-25 12:17 UTC, merged