fix: 이전글 다음 글 isDelete,isPrivate 조건 추가
wafflestudio/csereal-server pull request #151
Opened 2023-09-20 05:08 UTC by skfotakf

## 제목
fix: 이전글 다음 글 isDelete,isPrivate 조건 추가

### 한줄 요약
이전글 다음 글 에서 isDelete,isPrivate도 보도록 조건을 추가했습니다.

2023-09-20 09:40 UTC, huGgW requested changes
check 오류 확인하고 수정해주세요~

2023-09-21 04:39 UTC, skfotakf commented
ktlint 허우적거린다고 조금 늦었습니다 승인 부탁드려요!

2023-09-21 14:07 UTC, leeeryboy approved these changes
LGTM!

2023-09-22 04:49 UTC, huGgW approved these changes
굿

2023-09-22 05:37 UTC, merged