CICD: Add blocking backend api except frontend.
wafflestudio/csereal-server pull request #166
Opened 2023-09-26 13:50 UTC by huGgW

## CICD: Add blocking backend api except frontend.

### 한줄 요약

서버 ip를 제외한 곳에서의 백엔드 접속을 막았습니다.

2023-09-26 17:07 UTC, leeeryboy commented on caddy/Caddyfile
> +		path /api/* /sites/default/files/* /oauth2/authorization/idsnucse /swagger-ui/* /api-docs/*
이거 로그인은 그냥 리다이렉트 하는 형식이라 제한 풀어줘야할듯..  /api/v1/login, /api/v1/logout, /api/v1/login/oauth2/code/idsnucse, /oauth2/authorization/idsnucse
글고 파일 서빙하는 것도 풀어줘야 함 /api/v1/file/*

2023-09-27 02:46 UTC, huGgW commented on caddy/Caddyfile
> +		path /api/* /sites/default/files/* /oauth2/authorization/idsnucse /swagger-ui/* /api-docs/*
반영해서 수정했으!
근데 로그인 뭔가 잘 안되는거 같은데 이거떄문인가 그것도?

2023-09-27 02:52 UTC, leeeryboy commented on caddy/Caddyfile
> +		path /api/* /sites/default/files/* /oauth2/authorization/idsnucse /swagger-ui/* /api-docs/*
ㅇㅇㅇ 지금 안되는건 이거 때문인듯??

2023-09-27 02:53 UTC, leeeryboy approved these changes
👍

2023-09-27 04:32 UTC, huGgW commented on caddy/Caddyfile
> +		path /api/* /sites/default/files/* /oauth2/authorization/idsnucse /swagger-ui/* /api-docs/*
지금 수정해서 적용해놓았는데도 안댐...

2023-09-27 05:02 UTC, huGgW commented on caddy/Caddyfile
> +		path /api/* /sites/default/files/* /oauth2/authorization/idsnucse /swagger-ui/* /api-docs/*
일단 swagger만 막도록 수정함.

2023-09-27 05:30 UTC, leeeryboy requested changes
😭

2023-09-27 07:49 UTC, leeeryboy approved these changes

2023-09-27 17:07 UTC, merged