Feat/add language field
wafflestudio/csereal-server pull request #180
Opened 2024-02-07 08:32 UTC by skfotakf

## 제목
about에 language field 추가

### 한줄 요약
aboutEntity에 language field를 추가하고, AboutDto에서도 language을 추가하였습니다.

### 상세 설명

[988ab5687578f4bbc36f33c660fa7b14cedd1499]: aboutEntity에 language field을 추가하고 AboutDto에서도 language을 추가하였습니다.
language는 AboutDto에서 String으로 받고, ko 아니면 en을 받기로 하였습니다.
서비스 단에서 String을 Enum으로 변경하여 ko와 en만 입력이 가능하도록 하였습니다.

[a79d9a77f3cec3af8fc7fe3a6b0a12976396d5a2]: about을 read할 때 language을 PathVariable로 읽도록 하였습니다.

만들고 나니, 로컬에서 잘 작동하였습니다.

[1f029dc718be528bec00d72e807f571bf296d1ae]: ktlint에 맞게 코드 길이를 줄였습니다

### TODO

다른 엔티티들 중, 한국어 데이터 / 영어 데이터가 따로 있는 애들은 language 필드를 추가하려고 합니다.
마이그레이션할 때 검색 인덱스 추가하는건 이거 전체적으로 마무리하고 실행하려고 합니다.

TODO가 있다면 작성해주시고, 없다면 생략해주세요.

2024-02-07 10:22 UTC, huGgW requested changes

2024-02-07 10:22 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/common/repository/LanguageRepository.kt
이게 왜 `@Repository`로 등록되어있는지를 모르겠네...?
이거에 해당하는 domain이 있는거 같지 않고?
enum에 함수를 넣던지 하는 식으로 변경하는게 좋을듯

`makeStringtToLanguageType` 함수 생성한거 자체는 아주 좋음!

2024-02-07 10:22 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
PathVariable로 줘버리면 기존 uri에서 너무 변경이 많아지는 느낌...
이것보다는 query parameter로 language를 받도록 하고
주어지지 않는 경우 default로 ko를 주는 방식으로 하는게 변화를 최소화 시킬 수 있을 듯!

2024-02-07 10:22 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutEntity.kt
> +                language = languageType,
사소하긴 한데 이부분도 languageType을 한국어로 default를 정해주면 혹시나 빼먹어도 오류가 나지는 않을  거니까 그게 나을듯

2024-02-07 10:22 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/common/properties/LanguageType.kt
주석으로 dto로 통신할때 lowercase 사용합니다~ 이런 식으로 적어주면 좋을듯

2024-02-07 10:22 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
> +                language = this.language.toString().lowercase(),
이 코드 계속 반복되던데, 그냥 lowercase를 주는 함수를 enum class에 하나 만들어주는게 나을듯

2024-02-08 03:51 UTC, skfotakf commented
구구절절 맞는말이네 ㅎㅎㅎ 다 반영해서 커밋 올렸습니다 확인해주세여~!
[https://github.com/wafflestudio/csereal-server/pull/180/commits/85d87b84acb500d496fa04bfc642a99a20a18d97]: languageRepository 불필요해서 enum class로 함수 이동했습니다
[https://github.com/wafflestudio/csereal-server/pull/180/commits/3eae5756d5a936a95a45d59b575af64478b20729]: pathVariable로 받던 language을 requestParam으로 받도록 수정하였고, 진행하다가 engName이 아직 남아있는 곳들 발견해서 지웠습니다
[https://github.com/wafflestudio/csereal-server/pull/180/commits/a520f576748c9d86b0e7d5dc404f887d01de8200]: dto를 소문자로 받게 하던 함수 enum class로 이동시켰습니다

2024-02-09 05:41 UTC, huGgW requested changes
늦게 확인했습니다아...
귀찮겠지만 한번만 더 수정 부탁드립니다.

2024-02-09 05:41 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
> +        @RequestParam language: String?,
제가 전달이 미숙했군요 ㅠㅠ
여기 nullable하게 하지 말고 defaultValue를 정해주자는 의미였는데...
번거롭게 하여 죄송합니다

2024-02-09 05:41 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +    fun readAllDirections(language: String?): List<AboutDto>
이부분 다 nullable하지 않도록 변경해주세요오

2024-02-09 14:37 UTC, skfotakf commented
ㅠㅠㅠㅠㅠ 아닙니다 제대로 캐치를 못한 제가 미숙했네요.. 😢 다시 반영했습니다!
[39c2b22]: nullable하게 받던 language를 defaultValue를 받도록 수정

2024-02-09 14:42 UTC, huGgW approved these changes
고생 많이했습니다!
다음 pr도 비슷하게 수정해주시면 될듯합니다아

2024-02-09 15:19 UTC, merged