feat: academics 패키지에 language field 추가
wafflestudio/csereal-server pull request #181
Opened 2024-02-07 09:08 UTC by skfotakf

## 제목
feat: academics 패키지에 language field 추가

### 한줄 요약
academics 패키지의 academics, course 엔티티에 language field을 추가하였습니다.

### 상세 설명

[50069a25359c45734e2b8f0d61df34a999b233a1]: academics 엔티티에 language field을 추가하고, dto에도 language을 추가하였습니다. 

[c38adba4542da2b018c6fe9803be0755d5f60459]: course 엔티티에 language field을 추가하고, dto에도 language을 추가하였습니다. 

[29dfa404284f8a9ba0f6ecbe4c170bfa194fcfbb]: readAllCourses, readCourse에 language을 parameter을 추가하였습니다.
academics read는 안 건드렸는데, 지금 페이지는 academics에서 영어 부분이 거의 없어서 일단 냅뒀습니다.

feat/add-language-field 브랜치에서 만든 languageRepository을 기반으로 해서 그 브랜치에서 하위 브랜치를 팠는데, pr을 feat/add-language-field <- feat/add-language-field-academics로 하면 되나요? base을 develop으로 하려고 하니까 이전 커밋도 다 리뷰를 요구해서 base을 feat/add-language-field로 설정했습니다.

### TODO
모든 엔티티에서 language 필드를 추가하려고 했는데, 뭔가 마이그레이션을 실제로 하나 해보고 language을 계속해서 추가하려고 합니다. 그래서 member 패키지에 language 추가하고 행정직원 마이그레이션 진행해볼게요!

2024-02-07 10:27 UTC, huGgW requested changes

2024-02-07 10:27 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
얘도 마찬가지로 queryparameter로 하고 default값 지정해주세요

2024-02-07 10:27 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/AcademicsDto.kt
> +                language = this.language.toString().lowercase(),
이 부분들도 앞의 PR 해결하고 enum에 있는 method 활용하면 좋을듯!

2024-02-11 02:10 UTC, skfotakf commented
[8b59519]: languageRepository를 삭제하고 그 안의 내용을 LanguageType의 메서드로 옮겼으며, academicsEntity의 name은 nullable로 바꿨습니다
[ae8b910]: language을 requestParam으로 받도록 하였습니다
[fa1bc8f]: academicsEntity의 name 속성을 그대로 둘 것이라서 nullable 만들었던 걸 다시 되돌려 놓았습니다

2024-02-11 03:25 UTC, huGgW approved these changes
고생했어어!

2024-02-11 06:42 UTC, merged