fix: about, academics, admissions 패키지 수정
wafflestudio/csereal-server pull request #25
Opened 2023-08-19 03:47 UTC by skfotakf

## 제목
fix: about, academics, admissions 패키지 수정

### 한줄 요약
세 패키지에서 api 주소를 바꾸고, 각각의 패키지에 postType을 추가했습니다. 

### 상세 설명

[9d33d4a] , [b6fb6f4]: 두 패키지에서 한 게 거의 같아서 합치겠습니다
주소를 정한 규칙이 화요일에 준형이랑 얘기한 거랑도 달라지고, 프론트에게 전달되는 것도 많이 바뀌는 규칙이라서 설명드리겠습니다.
규칙은 postType을 enum으로 따로 두고, studentType은 그냥 string으로 두기로 했습니다
또한 postType은 requestParam으로 받고 about, admissions 같은 대항목이나 studentType은 pathVariable로 받고 있습니다
가장 마지막 항목 전까지는 /로 받고, 가장 마지막 항목이 세부항목들로 갈리면 postType(requestParam)으로 받도록 했습니다.

이러한 규칙으로 나머지 패키지 모두 바꿀 예정입니다.
만약 개선했으면 하는 점, 혹은 반대하는 점이 있다면 pr로 리뷰 부탁드려요

## 드리고자 하는 말

이러한 규칙을 적용하게 되면 프론트도 변경점이 상당하기 때문에 빨리 메인까지 pr로 보내야 할 거 같아요.
제 계획은, 일부 패키지 수정한걸로 백에서 허락 맡고, 얘를 develop으로 pr하고,  나머지 패키지를 합의된 규칙으로 바꾸고, 다시 develop으로 pr해서, 한번에 프론트에게 통일된 규칙을 전달하고 싶습니다.

원래는 모든 패키지를 한번에 pr하는 것도 생각했지만, 그렇게 패키지에 많은 점이 변경되면 리뷰가 배로 느려진다는 것을 저번주에 알게 되어서요. 절반만 보내드려요.

**만약 리뷰가 늦어진다면, 현재 pr에서 커밋을 추가하여 다른 패키지들을 모두 수정할 예정입니다.**
오늘 저녁까지 안하면 백분들이 봐야할 리뷰가 두배로 늘어날 거예요.. ㅠㅠ

오늘 밤부터 다시 작업을 시작할테니 그전에 리뷰 부탁드려요!

### TODO

다른 패키지들도 수정

2023-08-19 09:20 UTC, huGgW requested changes
1. path variable을 enum 처리한 부분은 변경이 필요해보입니다. **자동으로 해당 enum name으로 변환해서 확인해보도록 변경해주세요.**
2. 보통 POST의 경우 path variable과 query parameter를 사용하지 않고 필요한 정보가 있으면 request body에 해당 정보를 포함시켜서 전송합니다. 이 부분을 또 수정하면 프론트와의 논의도 다시 필요할 거 같아 이대로 진행해야 될 거 같지만, 다른 API를 구성하실 때 참고해주세요.
3. Student Type을 enum에서 string으로 변경하신 이유가 궁금합니다.

2023-08-19 09:20 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +        val enumPostType = enumPostTypes[stringPostTypes.indexOf(postType)]
이 부분은 실수로 한 곳을 누락하거나 오타가 날 경우 알아채기가 굉장히 어려워 보입니다.
PathVariable 값에서 '-'를 '_'로 바꾸고, case를 모두 UPPERCASE로 변경한 후 enum에서 탐색하면 수동으로 할 필요없이 해결될 수 있어 보입니다.

2023-08-19 09:20 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
> +        val enumPostType = enumPostTypes[stringPostTypes.indexOf(postType)]
이 부분도 위에서 언급한 바와 마찬가지로 처리해주세요.

2023-08-19 09:20 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
>          }
이 부분은 when으로 처리하면 조금 더 깔끔해보여요...! (지극히 개인적인 취향)

2023-08-20 12:05 UTC, skfotakf commented
리뷰 잘 반영해서 다시 제출하겠습니다. 2번에서 create api 관련은... 제가 잘 알지 못하니까 이리 바뀌고 저리 바뀌네요 정말 웁니다 울어요 😢 일단 지금은 pathVariable로 밀고 나가겠습니다

2023-08-20 13:07 UTC, skfotakf commented
string을 enum으로 변경하는 코드 작성, when으로 변경 모두 처리했습니다 리뷰 부탁드려요!

2023-08-20 15:02 UTC, leeeryboy commented
저도 혁준이형 의견처럼 POST에서는 꼭 필요한 경우를 제외하고는 Requestbody를 이용하는게 좋을것 같습니다.
REST API 설계 측면에서만 의견을 좀 내보자면, 너무 프론트 의존적이지 않아도 될것 같고(어느 정도는 어쩔수 없지만),
self-descriptive 하면 좋을것 같아요. 물론 일정이 빠듯하고 프론트와 혼동이 있을 수 있어서 의견을 모두 반영해 달라는 뜻은 아니지만, 이런식으로 설계하면 어떨까 싶습니다.

## 입학
GET /admissions?type=aaa
POST /admissions (RequestBody에 AdmissionType)

## 학사 및 교과
GET /academics?student-type=aaa&post-type=bbb
POST /academics (RequestBody에 StudentType, PostType)

_**교과목 패키지 분리**_
GET /course?type=aaa
POST /course (RequestBody에 CourseType)

_**장학금 패키지 분리**_
GET /scholarship?type=aaa
POST /scholarship (RequestBody에 ScholarshipType)

## 소개
GET /about?type=aaa (동아리,시설,찾아오는길 모두 통합)
POST /about (RequestBody에 AboutType)

2023-08-20 23:51 UTC, skfotakf commented
네 requestBody를 이용해야 한다는 건 저도 알겠습니다
다만 그건 유지보수 때 다시 바꿔나가고 지금은 pathVariable를 쓰겠다고 말씀을 드렸는데
승인이 안된 점에서 결국 지금 다시 프론트랑 이야기 해오라는 뜻으로 받아들이면 될까요?

2023-08-21 01:58 UTC, leeeryboy commented
오늘 회의에서 논의 한번 해보고 확정하고 가면 좋을것 같아요.
교과목이랑 장학금 API uri 변경 제안은 어떻게 생각하시나요?

2023-08-21 12:06 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
> +    }
1. slide하고 notice하고 분리하는 것이 좋아보입니다. 함수는 작게 나눌수록 이득!
2. makeNoticeEntity도 repository에서보다 service에서 호출하는 것이 좋아보여요.

2023-08-21 12:06 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
> +    }
1. slide하고 notice하고 분리하는 것이 좋아보입니다. 함수는 작게 나눌수록 이득!
2. makeNoticeEntity도 repository에서보다 service에서 호출하는 것이 좋아보여요.

2023-08-21 12:06 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
> +            .limit(5).distinct().fetch()
이런 숫자들은 query parameter로 controller에서 받는 식으로, 아니면 적어도 service에서는 하드 코딩해도 repository단에서는 변수로 받아주면 좋을거 같아요!

2023-08-22 05:49 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
> +    @Transactional
사소한 부분이지만 Custom 대신 그냥 MainRepository 타입을 쓰고
Transactional에는 readOnly 붙이면 좋을것 같아요

2023-08-23 10:33 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
> +            .limit(5).distinct().fetch()
지금 반드시 바꿔야하는 건 아니니까 일단 올리고 리뉴얼 후에 논의해도 괜찮을까요?

2023-08-23 10:33 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
> +    }
1. 넵 작게 나눴습니다
2. makeNoticeEntity는 없앴습니다!

2023-08-23 10:34 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
> +    @Transactional
둘다 반영했습니다

2023-08-24 06:44 UTC, leeeryboy approved these changes
고생하셨습니다

2023-08-24 07:18 UTC, huGgW approved these changes
고생하셨습니다!!

2023-08-24 12:14 UTC, merged