로그인 취약점 수정 및 Caddyfile.dev 추가
wafflestudio/csereal-server pull request #295
Opened 2024-07-12 14:18 UTC by leeeryboy

## enable csrf + Caddyfile.dev

### 한줄 요약

deprecated 된 filter chain 메서드들 변경하면서 csrf disable 에 해당하는 부분 제거, dev 서버용 Caddyfile 별도 생성

### 상세 설명

[b854b614806fe211ff2a8f70c5c03f4142299adf]: spring security 수정

[210e23860675e96e643c1177621dd5a44b52f0bb]: dev Caddyfile 생성 및 워크플로우 수정

### TODO

dev 배포 잘 되는지 테스트, 로그인 테스트

2024-07-12 14:20 UTC, leeeryboy commented
@huGgW 혹시 gitignore에 caddy/* 는 왜 추가한거야?

2024-07-13 03:28 UTC, huGgW commented
> @huGgW 혹시 gitignore에 caddy/* 는 왜 추가한거야?

아 로컬에서 테스트하면 다른 파일도 저기 생겨서 그거 제외허려도 추가했었을걸

2024-07-13 03:54 UTC, huGgW approved these changes
LGTM!

2024-07-13 06:58 UTC, huGgW requested changes

2024-07-13 06:58 UTC, huGgW commented on caddy/Caddyfile.dev
> +		path /swagger-ui/* /api-docs/* /api/v1/search/refresh
여기 path 부분은 제거해야될듯 (swagger 관련 이슈)

2024-07-13 07:40 UTC, leeeryboy commented on caddy/Caddyfile.dev
> +		path /swagger-ui/* /api-docs/* /api/v1/search/refresh
아예 제거할게 근데 우리 스웨거 리버스 프록시는 언제 사라졌었음?

2024-07-13 07:49 UTC, leeeryboy commented on caddy/Caddyfile.dev
> +		path /swagger-ui/* /api-docs/* /api/v1/search/refresh
path /swagger-ui/* /api-docs/* 는 prod에서도 의미가 없을듯? 지우면 그냥 프론트로 가는거 아님? ㅋㅋㅋ

2024-07-13 15:27 UTC, huGgW commented on caddy/Caddyfile.dev
> +		path /swagger-ui/* /api-docs/* /api/v1/search/refresh
어 그러게 저거 언제 지워졌지 ㅋㅋㅋㅋ? 지운 기억이 없는데 흠...

2024-07-13 16:58 UTC, leeeryboy commented on caddy/Caddyfile.dev
> +		path /swagger-ui/* /api-docs/* /api/v1/search/refresh
Approve plz

2024-07-14 03:29 UTC, huGgW approved these changes
LGTM

2024-07-14 07:57 UTC, merged