Feat/post2
wafflestudio/csereal-server pull request #3
Opened 2023-07-26 01:51 UTC by skfotakf

## 제목
공지사항 수정, 삭제, 태그

### 한줄 요약

ExceptionHandler, updateNotice, deleteNotice, Tag 엔티티, noticeTag 연관 엔티티 추가

### 상세 설명

[068225a]: 예외가 나올 때 처리하는 기능을 추가했습니다. @Valid로 인해 오류 떴을 때 메시지 전송 / csereal 내부 규정 오류 /  db에서 중복된 값 있을 때 나오는 예외를 처리했습니다.

[8d8d5cd]: 공지사항을 수정하는 기능을 추가했습니다. _@Valid을 통해 제목이 빈칸이거나, 내용이 빈칸이면 오류 메시지가 뜨도록 했습니다._ -> 확인해보니 내용을 ""으로 전송해도 전송이 잘 되네요.. 이거는 다음 pr에 수정하도록 할게요. NoticeEntity에서 isPublic 등의 기타 칼럼을 추가했습니다 

[0382376]: 공지사항을 삭제하는 기능을 추가했습니다. soft_delete 방식을 적용하여서, 삭제할 때 db 상에서 없어지는 게 아니라 isDeleted = true가 되도록 했습니다.

[3f2e94d]: TagEntity, NoticeTagEntity 엔티티를 추가하고, 공지사항에 태그를 추가하기 전에 우선 태그를 등록하는 기능을 추가했습니다.

[be6d433]: 공지사항을 올릴 때 태그도 같이 올리고, 수정할 때 태그도 같이 수정할 수 있도록 했습니다.

[c349869]: 혼자서 만들때는 로컬 db에 연결해서 하는데, 깜박하고 안 없앴네요. 다시 없는 상태로 올렸습니다.

### TODO
@Valid 메시지가 적용되도록 할 것. 다음으로는 페이지네이션 생각 중

2023-07-26 05:05 UTC, leeeryboy requested changes

2023-07-26 05:05 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +        }
여기도 위에 말한것처럼 notice.noticeTags 비우고 객체끼리 위에서 만든 편의 메서드로 연결시킨 다음 notice.save 만 하는게 깔끔할것 같습니다.

2023-07-26 05:05 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +    }
@Transactional 이 필요해보이는데, 어제 회의에서 태그는 그냥 고정으로 가져가자 하면 enrollTag 기능 자체가 딱히 필요없을것 같기도 합니다.

2023-07-26 12:06 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
> +    @PutMapping("/{noticeId}")
네 수정하겠습니다

2023-07-26 12:07 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
> +        return ResponseEntity<String>("삭제되었습니다. (noticeId: $noticeId)", HttpStatus.OK)
네 수정했어요~

2023-07-26 12:24 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeTagEntity.kt
> +    @ManyToOne(cascade = [CascadeType.PERSIST])
1. 연관관계 있을 때 부모 자식을 같이 관리하려고 하면 CascadeType이 필요하다고 해서 가져왔는데, 좀 더 찾아보니 불필요하다고 판단되네요. 지우도록 하겠습니다
2. fetchType.LAZY을 언제 넣어야 하는지 잘 몰랐는데, 찾아보니 횟수를 줄이면서 조회하기 좋다고 생각되네요. 수정하겠습니다

2023-07-26 12:24 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagEntity.kt
> +    @OneToMany(mappedBy = "tag", cascade = [CascadeType.PERSIST])
지웠습니다

2023-07-26 12:25 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/CreateNoticeRequest.kt
> +    val description: String,
다음 pr에 반영하려고 했는데, 같이 수정해서 올리겠습니다!

2023-07-26 14:41 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
>          noticeRepository.save(newNotice)
그냥 cascade 관계 끊으려다가 그래도 둘이 연관되어 있으니 객체끼리 연결하는게 맞겠다 싶어서 말한대로 새롭게 연관 편의 메서드 도입했습니다 처음 듣는 내용인데 덕분에 잘 적용했습니다 감사합니다

2023-07-26 14:46 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +    }
아.. 이거는 가끔 db 갈아엎고 태그 만들 때 쓰고 있는 애라서 나중에 없애도록 할게요.

2023-07-26 14:47 UTC, skfotakf commented
pr 리뷰 주신 거 수정해서 반영했습니다

2023-07-27 03:14 UTC, leeeryboy reviewed
한가지 더 코멘트할게 있는데, 지금은 태그를 id로 받는 형식으로 구현된거 같은데, db 상에서 id가 혹시라도 바뀔일이 있을수도 있으니 태그 이름으로 request 받도록 변경하는건 어떻게 생각하시나요?

2023-07-27 03:14 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +            notice.noticeTag = mutableSetOf()
`notice.noticeTag.clear()` 가 의미가 명확하지 않을까요?

2023-07-27 03:14 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +            for (i: Int in 0 until request.tag.size) {
`tag in request.tag`

2023-07-27 03:14 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +        for (i: Int in 0 until request.tag.size) {
`for (tag in request.tag)` 로 바꾸면 가독성이 좋아질 것 같습니다.

2023-07-27 03:14 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +                )
이렇게 하면 noticeTag 에 notice를 두번 지정해주는셈이 돼서, 지금 noticeTag 가 중간테이블이니까 notice 에 편의 메소드를 만들지 않고 noticeTag에 static으로 createNoticeTag란 함수를 만들어서 엔티티를 생성함과 동시에 상호간에 연결시켜주는게 낫지 않을까 싶어요.

2023-07-27 03:14 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +                    )
위에서 말한 부분과 동일

2023-07-27 05:25 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/CreateNoticeRequest.kt
> +    val description: String,
![image](https://github.com/wafflestudio/csereal-server/assets/86216809/575d93c5-cc95-454c-829c-a3de8764b391)
description " "으로 넣어도 오류메시지 잘 나옵니다

2023-07-27 05:29 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +        if (request.tag != null) {
프론트에서 수정사항을 보낼때 tag에서 변화가 없는 상황이면 null을 보내는 상황을 생각했습니다. 일반적으로 tag 변화 없어도 수정때 null로 보내는 게 아니라면 말해주면 수정하겠습니다. 케바케면 프론트랑 논의하고 거기에 맞출게요

2023-07-27 05:31 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
> +    var noticeTag: MutableSet<NoticeTagEntity> = mutableSetOf()
네

2023-07-27 05:42 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +            notice.noticeTag = mutableSetOf()
수정했습니다

2023-07-27 05:44 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +        for (i: Int in 0 until request.tag.size) {
수정했습니다

2023-07-27 07:41 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/CreateNoticeRequest.kt
> +    val description: String,
아 제가 NotNull 인 경우랑 착각했나보네요 확인 감사합니다.

2023-07-27 07:42 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +        if (request.tag != null) {
네 이 부분은 프론트랑 소통이 필요해보이네요

2023-07-27 10:34 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
> +                )
companion object로 static 표현해서 올렸습니다. 사실 좀 헷갈리는 부분이긴 하지만 일단 기능은 구현됩니다

2023-07-27 10:40 UTC, skfotakf commented
pr 리뷰 주신 것 수정해서 올렸습니다. 태그 이름에 대해서도 프론트랑 이야기하고 정하는 건 어떨까요? 나머지는 다 관련하여 댓글 달았습니다

2023-07-28 08:16 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeTagEntity.kt
> +            tag.noticeTags.add(NoticeTagEntity(notice,tag))
변수에 assign 하고 밑에 argument로 넣어줘야할거 같습니다.
ex) `val noticeTag = NoticeTagEntity(notice,tag)`

2023-07-28 08:45 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeTagEntity.kt
> +            tag.noticeTags.add(NoticeTagEntity(notice,tag))
넵!

2023-07-28 08:56 UTC, leeeryboy approved these changes
고생했어용

2023-07-28 11:26 UTC, merged