feat: 소개 탭 CRUD
wafflestudio/csereal-server pull request #314
Opened 2024-08-28 12:59 UTC by leeeryboy

## 졸업생 진로 현황 제외 소개 탭 CRUD api

### TODO

배포 전 about_language 테이블 생성 및 연결(시설, 찾아오는길), about 테이블 year, eng_name 컬럼 삭제

2024-09-01 05:55 UTC, huGgW requested changes

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/CreateClubReq.kt
> +}
이거 dto나 response로 들어가는게 나을듯?

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/v1/AboutController.kt
> +
v2로

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/v1/AboutController.kt
> +
v2로

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/v1/AboutController.kt
> +
v2로

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/v1/AboutController.kt
> +
v2로

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/v1/AboutController.kt
> +
v2로

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/CreateClubReq.kt
> +
뭔가 dto, dtowithid 보다는 id 없는게 reqbody, id  있는걸 dto로 네이밍 하는게 낫지 않나 싶긴 하지만 사소함.

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutRepository.kt
>  }
지금 안쓰이는거 같은데 어디 쓰일 예정?

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +
image를 제거하려는 경우도 고려해야 될듯..? (이미지가 반드시 필요한게 아니라면)

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/UpdateAboutReq.kt
> +    val deleteIds: List<Long>
deleteAttachmentIds 이런식으로 바꾸는게 직관적일듯!

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +    }
여기도 이미지 null일 경우도 존재한다면 이미지 제거하는 경우도 고려해야될듯?

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +        }
여기도

2024-09-01 05:55 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +    override fun deleteFacility(id: Long) {
@Transactional

2024-09-01 13:05 UTC, Limchansol commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/UpdateAboutReq.kt
> +    val deleteIds: List<Long>
지나가다 들렀습니다👀 다른 편집들(소식탭, 학사 및 교과) 첨부파일 삭제는 지금 `deleteIds`일 거라 만약 바뀌게 된다면 같은 기능이니 네이밍 통일해주면 좋을 것 같다는 작은 의견입니다ㅏ 달라도 별 문제 없긴 하지만 혹시라도 헷갈릴 것을 대비해서,,,🥹

2024-09-02 01:03 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/UpdateAboutReq.kt
> +    val deleteIds: List<Long>
아 그렇다면 일단 그냥 두는갓도 괜찮을지도?

2024-09-02 06:05 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutRepository.kt
>  }
아 이거 쓰려다가 id 기준으로 바꾸면서 안써서 지우겠슴

2024-09-02 06:50 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +
맞네 생각 안하고 있었음 땡큐

2024-09-03 16:46 UTC, huGgW approved these changes
굿굿!

2024-09-04 03:52 UTC, merged