feat: about, member, news, seminar 메인 이미지 업로드 추가
wafflestudio/csereal-server pull request #38
Opened 2023-08-24 18:53 UTC by skfotakf

## 제목
feat: about, member, news, seminar 메인 이미지 업로드 추가

### 한줄 요약
네 개의 패키지에 사진을 업로드하는 기능을 추가하였고, 네 패키지의 게시글을 get하면 image url을 얻을 수 있습니다.

PR 요약해주세요

### 상세 설명

[2361230]: imageUpload 기능을 추가했습니다. 이렇게 하니 로컬에서는 C 드라이브 바로 밑에 var/myapp/images가 생성되어서 이미지와 썸네일 이미지 두개가 저장되었습니다. (application.yaml을 한번 봐주시면 감사하겠습니다. 이렇게 작성하면 main에 올린 이후 저희 서버에서도 이미지가 잘 저장이 되나요? ㅠㅠ)

[b70cd2f]: about과 member에 사진을 올릴 수 있도록 하였습니다. 프론트 쪽에서 image을 multipart file로 보내주겠다고 하셔서, requestPart을 통해 json 데이터와 Multipart File을 따로 보내도록 하였습니다. 

[6388c7e]: news와 seminar에도 이전 커밋에 적용한 내용을 추가하였습니다.

[65f4c8c]: 코드가 겹치는 점이 많아 보여서, 이를 하나로 합쳤습니다.

[da0f6d4]: 이미지 업로드에 gif는 안들어간다고 해서 뺐습니다.

### TODO
사실은 산넘어 산입니다. deleteImage도 추가해야하고, downloadImage도 추가해야 하고, attachments도 업로드, 삭제, 다운로드에 걔네는 순서 변경까지 넣어야 하네요
그거까지 손대면 pr 제출도 늦고 리뷰도 오래 걸릴거 같아 여기에서 제출합니다
하위 브랜치 파서 위에서 얘기한 todo들 시도할 예정입니다

좋은 리뷰 부탁드립니다! 감사합니다

2023-08-27 02:44 UTC, huGgW requested changes
고생하셨습니다.
application yaml 설정과 image url 관련 부분만 신경써주시면 될 거 같아요.

2023-08-27 02:44 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/common/controller/ContentEntityType.kt
> +}
👍

2023-08-27 02:44 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
> +        }
이 부분은 수정이 필요해보입니다.
1. endpoint가 hard coding되어 있어 서버 endpoint가 변할 수도 있고, 로컬에서도 테스트하기 힘들 것 같습니다. 이 부분은 수정이 필요해보입니다.
2. server의 directory를 root 레벨부터 그대로 보여주는 방식은 좋지 않아보입니다. (docker image 내부 경로라서 큰 영향은 없긴 할 거 같긴 합니다만...) 보통 서버 프로젝트 최상단을 기준으로 상대 경로로 uri를 지정하는 것으로 알고 있습니다. 차라리 이미지, 혹은 파일에 대한 GET API를 따로 만드는 것은 어떨까 생각합니다.
3. 추가적으로 이 method가 너무 많은 부분에서 똑같이 나타나는것 같습니다. 어디 한 군데로 모을 수 있다면 깔끔할거 같긴 합니다.

2023-08-27 02:44 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/service/ImageService.kt
> +    }
👍
(그나저나 Transational은 없어도 되나요? 궁금합니당)

2023-08-27 02:44 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/dto/ImageDto.kt
> +}
Filename을 uuid를 이용해서 생성하는 것으로 알고 있는데,
(image에서는 필요없을 지도 모르겠지만) 표시하고자 하는 이름도 저장해둬야 되지 않나요...??
궁금해서 여쭤봅니다.

2023-08-27 02:44 UTC, huGgW commented on src/main/resources/application.yaml
> +    path: /var/myapp/image/
local하고 prod하고 분리해서 작성해주세요.

2023-08-28 08:31 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/dto/ImageDto.kt
> +}
저도 첨부파일에는 originalFilename 도 필요할것 같습니다 + filename과 extension을 구분하는 이유가 궁금합니다. 보통 filename에 extension까지 포함 아닌가요?

2023-08-28 08:31 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/service/ImageService.kt
> +        }
setUUIDFilename을 둔 이유가 궁금합니다. 무조건 orginalFilename 이랑 uuid(or timeMillis) 로 생성하는 방식이랑 어떤 차이인가요?

2023-08-28 08:31 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/service/ImageService.kt
> +        val filename = "${timeMillis}_$uuid"
filename에 extension까지 포함해서 관리하는게 편할것 같습니다

2023-08-29 08:40 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
> +        }
이부분에 대해서는 나중에 도와주시면 감사하겠습니다

2023-08-29 08:43 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/service/ImageService.kt
> +    }
connectImageToEntity는 imageService 내부에서만 쓰는 거라서 private를 추가했는데, private를 추가하니 transactional은 받지 않는다고 되어있네요

2023-08-29 08:51 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/dto/ImageDto.kt
> +}
filename 관련해서 컴공 사이트를 뒤져보니, image 이름이 uuid가 아니라 업로드한 그대로의 이미지 이름이 나오네요. 그래서 기본 이미지를 $originalFilename_$timeMillis 으로 수정했습니다. 다만 혹시나 uuid을 필요로 할지도 모르니까 uuid를 지우지 않고 남겨둡니다

혹시나 extension을 나눠서 담아두면 좋지 않을까 싶어서 담긴 했고, 사실 강조하시는 만큼 둘이 반드시 하나로 합쳐져야 하는 건지 잘 모르겠긴 합니다(밑에 여러번 언급을 하시길래..) 다만 저도 만일을 대비해서 담아둔 정도니까 두분 합쳐서 담는게 좋다고 생각하면 이후에 수정하겠습니다.

2023-08-29 08:51 UTC, skfotakf commented on src/main/resources/application.yaml
> +    path: /var/myapp/image/
도와주시면 감사하겠습니다

2023-08-29 08:53 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/database/ImageEntity.kt
> +    var seminar: SeminarEntity? = null,
사실 양방향으로 한건 제가 참고한 다른 코드에서 양방향으로 한 정도라서...
그래서 건의를 보고 양방향이 필요한 이유를 생각해봤습니다
저 나름대로 생각해본 결과, 말하신 대로 딱히 image.about 등이 쓰이는 경우는 없네요
말씀한 대로 양방향을 단방향으로 바꾸고, ImageEntity의 매핑 관계도 지웠습니다.
이렇게 해도 이미지는 잘 업로드되는 것을 확인하였습니다

2023-08-29 08:54 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/image/service/ImageService.kt
> +        }
저도 다른 코드에서 참고한 거라서.. 일단 위에서 언급하다시피 기본을 originalFilename으로 하되, uuid 기능은 남겨놨습니다

2023-08-29 13:11 UTC, huGgW requested changes

2023-08-29 13:11 UTC, huGgW commented on src/main/resources/application.yaml
> +    path: /var/myapp/image/
/app/image 로 바꿔주세요!
(서버 실행되는 workdir가 /app이라서 그렇습니다.

2023-08-29 13:12 UTC, huGgW approved these changes
굳!

2023-08-29 13:15 UTC, merged