feat: attachments 패키지 추가, news와 seminar request에 attachments 추가
wafflestudio/csereal-server pull request #43
Opened 2023-08-29 14:24 UTC by skfotakf

## 제목
feat: attachments 패키지 추가, news와 seminar request에 attachments 추가

### 한줄 요약
image 하는 것에서 attachments 버전을 추가시켰습니다. 첨부파일은 대부분의 패키지에 들어가야 하는데 그중에서 news, seminar을 올려요

PR 요약해주세요

### 상세 설명

[33d20e0]: attachments 패키지를 추가했고, news에서 attachments를 추가할 수 있도록 했습니다.

[3149e2d]: seminar에서 attachments를 추가할 수 있도록 했습니다.

### TODO

공지사항, academics 등등에서 다 추가할 수 있도록 해야죠

2023-08-29 15:20 UTC, leeeryboy requested changes

2023-08-29 15:20 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
> +    var attachments: MutableList<AttachmentEntity> = mutableListOf(),
첨부파일 쪽에 fk + 여기는 mappedby

2023-08-29 15:48 UTC, huGgW requested changes

2023-08-29 15:48 UTC, huGgW commented on src/main/resources/application.yaml
attatchment 경로는 분리해서 만들어주세요!

2023-08-30 03:09 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/database/AttachmentEntity.kt
> +    val isDeleted : Boolean? = true,
isDeleted 는 왜 true 가 default 인가요?

2023-08-30 03:10 UTC, leeeryboy approved these changes

2023-08-30 03:43 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/database/AttachmentEntity.kt
> +    val isDeleted : Boolean? = true,
..! 잘못 썼네요 isDeleted는 false가 default가 되어야 합니다
수정했습니다

2023-08-30 06:58 UTC, huGgW approved these changes

2023-08-30 13:18 UTC, merged