feat: academics, about request에 attachments 추가
wafflestudio/csereal-server pull request #46
Opened 2023-08-29 15:52 UTC by skfotakf

## 제목
feat: academics, about request에 attachments 추가

### 한줄 요약
academics, about, course request에 attachments를 추가했습니다.

### 상세 설명

[d42dbbf]: about request에 attachments를 추가했습니다.

[6edf7ef]: academics와 course request에 attachments를 추가했습니다. 교과목 정보에서 첨부파일이 필요한건 아니지만, 어차피 프론트에서 안받으면 되니까 일단 모두에서 attachments 주면 좋겠다고 해서 추가했습니다.

### TODO

다른 패키지에 attachments 추가하겠습니다

2023-08-30 05:45 UTC, leeeryboy requested changes

2023-08-30 05:45 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
> +        fun of(entity: AboutEntity, imageURL: String?, attachments: List<AttachmentResponse>?) : AboutDto = entity.run {
리스트 응답은 항상 null 대신 빈 리스트를 주면 좋을것 같습니다!

2023-08-30 05:45 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +        val attachments = attachmentService.createAttachments(newAbout.attachments)
지금 argument로 attachments를 받고 있는데 똑같은 변수명을 사용하면 혼동 가능성이 있어서 attachmentResponses 같은걸로 변경하면 좋을것 같습니다.

2023-08-30 05:45 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/database/AttachmentEntity.kt
> +    val isDeleted : Boolean? = true,
false

2023-08-30 05:45 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
> +    fun createAttachments(attachments: List<AttachmentEntity>?): List<AttachmentResponse>?
응답은 not null

2023-08-30 05:45 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
> +            val saveFile = Paths.get("$totalFilename.$extension")
saveFile 선언할때 뒤에 extension 중복인것 같습니다

2023-08-30 15:28 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
> +    val attachments: List<AttachmentResponse>?,
DTO에서도 collection의 경우 null보다는 empty하게 표현하는 것이 좋습니다.
locations도 마찬가지긴 한데...
null이 없어도 되는 곳이면 null이 없을수록 좋습니다.

2023-08-31 01:10 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
> +    val attachments: List<AttachmentResponse>?,
저부분은 request할 때도 dto를 쓰고 있는데, reqeust에서는 attachments 리스트가 필요하지 않아서 넣었습니다. 9월 이후에 request response 분리하는거 같던데 그때는 다시 null을 없애도록 하겠습니다

2023-08-31 01:25 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
> +    fun createAbout(postType: String, request: AboutDto, image: MultipartFile?, attachments: List<MultipartFile>?): AboutDto
아.. 일단은 null로 보내겠습니다

2023-09-01 04:57 UTC, closed without merging