fix: notice 패키지 프론트에 맞게 협의
wafflestudio/csereal-server pull request #54
Opened 2023-09-01 17:21 UTC by skfotakf

## 제목
fix: notice 패키지 프론트에 맞게 협의

### 한줄 요약
notice 패키지를 프론트에 맞게 항목 등을 추가하였고, 체크한 것 고정해제+삭제 기능도 추가하였습니다.

PR 요약해주세요

### 상세 설명

[fa44f43608b597ca59476d88bcf9603cc13b29a6]: notice에도 첨부파일을 넣는게 가능하도록 했습니다. 로그인 부분은 어떻게 하는지 몰라서 일단 주석 처리하고 마지막 커밋에서 다시 복구시켰습니다.

[63402955fb41896702ca8e3a2a0cc182e759633a]: fix_with_front1에서 수정한 거 fix2에서도 똑같이 수정했습니다.

[50ee14b36f342e96741bb6d936b20c147d1dd01d]: 공지사항에서 isImportant 항목을 추가했습니다. isImportant = true라면 중요 공지사항으로 메인에 표시됩니다.

[c1f9589250d0f80317c82ba8e30e930e03b717c2]: 공지사항 전체 목록을 보여주는 화면에서 각 공지사항에 대해 첨부파일이 있는지를 알려달라고 해서 hasAttachment을 추가했습니다.

[13d1048343e112665d298d63b04bf1166def3b8f]: 전체적으로 update할 때 이미지나 첨부파일이 null이면 없어지는 걸 구현했어야 하는데, 그렇게 하지 않아서 추가했습니다.

[3f96a6f724ed7c276a8725511cb11bae7617a310]: 체크한 공지사항 선택삭제, 체크한 공지사항 선택 공지해제 기능을 추가하였습니다.

### TODO

패키지 하나씩 잡아가고 있습니다!

2023-09-01 19:46 UTC, huGgW requested changes

2023-09-01 19:46 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
> +
RequestBody에 대한 DTO를 정의해주세요.

2023-09-01 19:46 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
>          }
제가 알기로는 MainImage로의 OneToOne 관계에서 Cascade관련 설정이 되어있지 않은 것으로 알고 있습니다.
따로 정의되지 않은 경우 기본적으로 Cascading이 일어나지 않아서 여기서 null을 처리하더라도 mainImage 자체는 제거되지 않는 것으로 알고 있습니다.
이미 테스트를 해보셨고 잘 된다면 상관없지만, 아니라면 이 부분이 수정이 필요해 보입니다.

2023-09-01 19:46 UTC, huGgW commented on src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
>          }
저장되있는 파일을 실제로 제거하는 로직은 없는 것으로 알고 있습니다.
해당 부분 추가되어야 할 것 같습니다. (AttachmentService, MainImageService 단에 생성하여 사용하는게 깔끔할 것 같습니다.

2023-09-01 19:54 UTC, huGgW commented
추가적으로 한 가지 고려해야 될 사항이 있습니다. 앞선 PR에도 코멘트 남기긴 했는데요,
attachment 혹은 mainImage가 있는 게시물에 대한 update시의 동작입니다.
제가 이해한 바에 따르면 현재는 일부 파일만 변경, 혹은 아얘 변경이 되지 않아도 모든 파일, 이미지를 업로드해야 반영되는 것으로 알고 있습니다.
이 부분은 매우 비효율적인 방식으로 보입니다. 수정되는것이 좋아보입니다.

2023-09-02 09:17 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
> +
NoticeIdListRequest라는 새로운 DTO를 정의했습니다

2023-09-02 09:18 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
>          }
mainImage가 잘나타나긴 하는데, 제거는 또 그거랑 다른 거라고 이해했습니다.
슬랙에서 말한 거 따라서 mainImage의 isDeleted을 true로 만들었습니다.

2023-09-02 09:25 UTC, skfotakf commented on src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
>          }
말씀주신 대로, update는 컨트롤러 단에서 새로운 첨부파일 리스트(newAttachments: List<MultipartFile>)과 기존의 것에서 받고 싶은 것들의 리스트(attachmentsList: List<AttachmentResponse>)을 받도록 했습니다. 일단 리스트의 내용을 비교하여, 거기에 들어가있지 않은 애들은 빼버리는 작업을 하고, newAttachments을 통해 받고 싶은 애들은 새롭게 추가하는 걸로 했습니다. 

pdf1, pdf2가 있는데, newAttachments로 pdf3,pdf4를 주고, attachmentsList에서는 pdf1의 정보만 담겼을 때 response는 계획대로 pdf 1,3,4만 나와주고 2는 isDeleted+seminar null이 되었습니다. 해당 세미나를 다시 읽었을 때도 1,3,4만 response로 읽혔습니다. 다만 이렇게 하면 attachmentsOrder가 뒤죽박죽이 되는데 이건 다시 프론트와 협의해서 정하겠습니다.

해당 방법에 확신이 없어 일단 세미나 패키지에만 해당 변경사항을 커밋합니다 확인하고 리뷰 해주세요.

2023-09-02 12:26 UTC, huGgW approved these changes
고생하셨습니다!
순서도 포함하려면 나중에 구조가 조금 바뀔 수도 있긴 하겠네요!

2023-09-02 16:47 UTC, merged